name: pubspec_yaml
description: Dart library to access and manipulate content of pubpec.yaml files
version: 1.0.0
homepage: https://micropub.ommani.vn
publish_to: https://micropub-api.ommani.vn

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  collection: ^1.19.0
  functional_data: ^1.2.0
  json2yaml: ^3.0.1
  meta: ^1.16.0
  plain_optional: ^1.0.0
  sum_types: ^0.3.5
  yaml: ^3.1.2

dev_dependencies:
  analyzer: ^5.13.0
  build_runner: ^2.4.13
  dependency_validator: ^4.1.1
  functional_data_generator: ^2.2.0
  sum_types_generator: ^0.3.5
  test: ^1.25.8
